In [23]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import auc, roc_auc_score, roc_curve
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC

In [3]:
df = pd.read_csv("train.csv")

In [9]:
print(df.iloc[:,2])

0          blue-collar
1         entrepreneur
2           management
3              retired
4           management
5          blue-collar
6             services
7           technician
8               admin.
9        self-employed
10       self-employed
11          technician
12              admin.
13          management
14         blue-collar
15          technician
16          management
17             retired
18         blue-collar
19              admin.
20       self-employed
21             retired
22          management
23              admin.
24            services
25             retired
26          management
27            services
28         blue-collar
29          technician
             ...
27098           admin.
27099      blue-collar
27100      blue-collar
27101      blue-collar
27102       management
27103     entrepreneur
27104       management
27105       management
27106       management
27107           admin.
27108      blue-collar
27109         services
27110       management
27111       unemployed
27112      blue-collar
27113     entrepreneur
27114      blue-collar
27115       management
27116          retired
27117       management
27118      blue-collar
27119       technician
27120          retired
27121    self-employed
27122    self-employed
27123      blue-collar
27124         services
27125      blue-collar
27126        housemaid
27127         services
Name: job, Length: 27128, dtype: object

In [10]:
print(df.isnull())

          id    age    job  marital  education  default  balance  housing  \
0      False  False  False    False      False    False    False    False
1      False  False  False    False      False    False    False    False
2      False  False  False    False      False    False    False    False
3      False  False  False    False      False    False    False    False
4      False  False  False    False      False    False    False    False
5      False  False  False    False      False    False    False    False
6      False  False  False    False      False    False    False    False
7      False  False  False    False      False    False    False    False
8      False  False  False    False      False    False    False    False
9      False  False  False    False      False    False    False    False
10     False  False  False    False      False    False    False    False
11     False  False  False    False      False    False    False    False
12     False  False  False    False      False    False    False    False
13     False  False  False    False      False    False    False    False
14     False  False  False    False      False    False    False    False
15     False  False  False    False      False    False    False    False
16     False  False  False    False      False    False    False    False
17     False  False  False    False      False    False    False    False
18     False  False  False    False      False    False    False    False
19     False  False  False    False      False    False    False    False
20     False  False  False    False      False    False    False    False
21     False  False  False    False      False    False    False    False
22     False  False  False    False      False    False    False    False
23     False  False  False    False      False    False    False    False
24     False  False  False    False      False    False    False    False
25     False  False  False    False      False    False    False    False
26     False  False  False    False      False    False    False    False
27     False  False  False    False      False    False    False    False
28     False  False  False    False      False    False    False    False
29     False  False  False    False      False    False    False    False
...      ...    ...    ...      ...        ...      ...      ...      ...
27098  False  False  False    False      False    False    False    False
27099  False  False  False    False      False    False    False    False
27100  False  False  False    False      False    False    False    False
27101  False  False  False    False      False    False    False    False
27102  False  False  False    False      False    False    False    False
27103  False  False  False    False      False    False    False    False
27104  False  False  False    False      False    False    False    False
27105  False  False  False    False      False    False    False    False
27106  False  False  False    False      False    False    False    False
27107  False  False  False    False      False    False    False    False
27108  False  False  False    False      False    False    False    False
27109  False  False  False    False      False    False    False    False
27110  False  False  False    False      False    False    False    False
27111  False  False  False    False      False    False    False    False
27112  False  False  False    False      False    False    False    False
27113  False  False  False    False      False    False    False    False
27114  False  False  False    False      False    False    False    False
27115  False  False  False    False      False    False    False    False
27116  False  False  False    False      False    False    False    False
27117  False  False  False    False      False    False    False    False
27118  False  False  False    False      False    False    False    False
27119  False  False  False    False      False    False    False    False
27120  False  False  False    False      False    False    False    False
27121  False  False  False    False      False    False    False    False
27122  False  False  False    False      False    False    False    False
27123  False  False  False    False      False    False    False    False
27124  False  False  False    False      False    False    False    False
27125  False  False  False    False      False    False    False    False
27126  False  False  False    False      False    False    False    False
27127  False  False  False    False      False    False    False    False

        loan  contact    day  month  duration  campaign  pdays  previous  \
0      False    False  False  False     False     False  False     False
1      False    False  False  False     False     False  False     False
2      False    False  False  False     False     False  False     False
3      False    False  False  False     False     False  False     False
4      False    False  False  False     False     False  False     False
5      False    False  False  False     False     False  False     False
6      False    False  False  False     False     False  False     False
7      False    False  False  False     False     False  False     False
8      False    False  False  False     False     False  False     False
9      False    False  False  False     False     False  False     False
10     False    False  False  False     False     False  False     False
11     False    False  False  False     False     False  False     False
12     False    False  False  False     False     False  False     False
13     False    False  False  False     False     False  False     False
14     False    False  False  False     False     False  False     False
15     False    False  False  False     False     False  False     False
16     False    False  False  False     False     False  False     False
17     False    False  False  False     False     False  False     False
18     False    False  False  False     False     False  False     False
19     False    False  False  False     False     False  False     False
20     False    False  False  False     False     False  False     False
21     False    False  False  False     False     False  False     False
22     False    False  False  False     False     False  False     False
23     False    False  False  False     False     False  False     False
24     False    False  False  False     False     False  False     False
25     False    False  False  False     False     False  False     False
26     False    False  False  False     False     False  False     False
27     False    False  False  False     False     False  False     False
28     False    False  False  False     False     False  False     False
29     False    False  False  False     False     False  False     False
...      ...      ...    ...    ...       ...       ...    ...       ...
27098  False    False  False  False     False     False  False     False
27099  False    False  False  False     False     False  False     False
27100  False    False  False  False     False     False  False     False
27101  False    False  False  False     False     False  False     False
27102  False    False  False  False     False     False  False     False
27103  False    False  False  False     False     False  False     False
27104  False    False  False  False     False     False  False     False
27105  False    False  False  False     False     False  False     False
27106  False    False  False  False     False     False  False     False
27107  False    False  False  False     False     False  False     False
27108  False    False  False  False     False     False  False     False
27109  False    False  False  False     False     False  False     False
27110  False    False  False  False     False     False  False     False
27111  False    False  False  False     False     False  False     False
27112  False    False  False  False     False     False  False     False
27113  False    False  False  False     False     False  False     False
27114  False    False  False  False     False     False  False     False
27115  False    False  False  False     False     False  False     False
27116  False    False  False  False     False     False  False     False
27117  False    False  False  False     False     False  False     False
27118  False    False  False  False     False     False  False     False
27119  False    False  False  False     False     False  False     False
27120  False    False  False  False     False     False  False     False
27121  False    False  False  False     False     False  False     False
27122  False    False  False  False     False     False  False     False
27123  False    False  False  False     False     False  False     False
27124  False    False  False  False     False     False  False     False
27125  False    False  False  False     False     False  False     False
27126  False    False  False  False     False     False  False     False
27127  False    False  False  False     False     False  False     False

       poutcome      y
0         False  False
1         False  False
2         False  False
3         False  False
4         False  False
5         False  False
6         False  False
7         False  False
8         False  False
9         False  False
10        False  False
11        False  False
12        False  False
13        False  False
14        False  False
15        False  False
16        False  False
17        False  False
18        False  False
19        False  False
20        False  False
21        False  False
22        False  False
23        False  False
24        False  False
25        False  False
26        False  False
27        False  False
28        False  False
29        False  False
...         ...    ...
27098     False  False
27099     False  False
27100     False  False
27101     False  False
27102     False  False
27103     False  False
27104     False  False
27105     False  False
27106     False  False
27107     False  False
27108     False  False
27109     False  False
27110     False  False
27111     False  False
27112     False  False
27113     False  False
27114     False  False
27115     False  False
27116     False  False
27117     False  False
27118     False  False
27119     False  False
27120     False  False
27121     False  False
27122     False  False
27123     False  False
27124     False  False
27125     False  False
27126     False  False
27127     False  False

[27128 rows x 18 columns]

In [12]:
print(df.isnull().sum())

id           0
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [13]:
print(df["job"])

0          blue-collar
1         entrepreneur
2           management
3              retired
4           management
5          blue-collar
6             services
7           technician
8               admin.
9        self-employed
10       self-employed
11          technician
12              admin.
13          management
14         blue-collar
15          technician
16          management
17             retired
18         blue-collar
19              admin.
20       self-employed
21             retired
22          management
23              admin.
24            services
25             retired
26          management
27            services
28         blue-collar
29          technician
             ...
27098           admin.
27099      blue-collar
27100      blue-collar
27101      blue-collar
27102       management
27103     entrepreneur
27104       management
27105       management
27106       management
27107           admin.
27108      blue-collar
27109         services
27110       management
27111       unemployed
27112      blue-collar
27113     entrepreneur
27114      blue-collar
27115       management
27116          retired
27117       management
27118      blue-collar
27119       technician
27120          retired
27121    self-employed
27122    self-employed
27123      blue-collar
27124         services
27125      blue-collar
27126        housemaid
27127         services
Name: job, Length: 27128, dtype: object

In [14]:
df = pd.read_csv("train.csv")

In [15]:
print(df)

          id  age            job   marital  education default  balance  \
0          1   39    blue-collar   married  secondary      no     1756
1          2   51   entrepreneur   married    primary      no     1443
2          3   36     management    single   tertiary      no      436
3          4   63        retired   married  secondary      no      474
4          5   31     management    single   tertiary      no      354
5          6   29    blue-collar    single  secondary      no      260
6          7   37       services   married  secondary      no       52
7          8   32     technician    single  secondary      no      230
8          9   31         admin.    single  secondary      no        0
9         10   32  self-employed    single   tertiary      no     1815
10        11   35  self-employed    single   tertiary      no      353
11        12   34     technician  divorced  secondary      no     1451
12        13   34         admin.    single   tertiary      no      625
13        14   31     management  divorced   tertiary      no      883
14        15   38    blue-collar   married    primary      no     5839
15        16   71     technician   married   tertiary      no      383
16        17   62     management   married   tertiary      no      557
17        18   66        retired   married  secondary      no      154
18        19   46    blue-collar   married    primary      no      369
19        20   29         admin.    single   tertiary      no       89
20        21   28  self-employed   married   tertiary      no      112
21        22   67        retired   married    primary      no      708
22        23   42     management   married   tertiary      no        4
23        24   33         admin.  divorced  secondary      no      420
24        25   39       services    single  secondary      no      158
25        26   57        retired  divorced   tertiary      no       66
26        27   43     management    single   tertiary      no        0
27        28   46       services  divorced    unknown      no      973
28        29   31    blue-collar   married    primary      no      -81
29        30   36     technician    single  secondary      no      524
...      ...  ...            ...       ...        ...     ...      ...
27098  27099   31         admin.  divorced  secondary      no      525
27099  27100   29    blue-collar    single  secondary      no        0
27100  27101   46    blue-collar   married    primary      no      222
27101  27102   32    blue-collar   married  secondary      no       14
27102  27103   38     management   married   tertiary      no      551
27103  27104   36   entrepreneur   married   tertiary      no      247
27104  27105   59     management   married  secondary      no    -1246
27105  27106   44     management    single   tertiary      no     5063
27106  27107   40     management   married  secondary      no      752
27107  27108   35         admin.   married  secondary      no      348
27108  27109   33    blue-collar   married  secondary      no      661
27109  27110   43       services   married  secondary      no      823
27110  27111   51     management   married   tertiary      no      941
27111  27112   50     unemployed   married  secondary      no     3478
27112  27113   45    blue-collar   married    primary      no        0
27113  27114   41   entrepreneur   married   tertiary      no     1065
27114  27115   43    blue-collar   married    primary      no      -93
27115  27116   42     management   married   tertiary      no    27696
27116  27117   45        retired  divorced  secondary      no      187
27117  27118   30     management    single  secondary      no       19
27118  27119   48    blue-collar   married  secondary      no      750
27119  27120   27     technician   married   tertiary      no    10451
27120  27121   66        retired   married  secondary      no     3409
27121  27122   37  self-employed   married   tertiary      no     2211
27122  27123   59  self-employed  divorced   tertiary      no     2979
27123  27124   42    blue-collar   married    primary      no     1455
27124  27125   34       services    single  secondary      no      719
27125  27126   36    blue-collar    single    primary      no       49
27126  27127   33      housemaid   married    primary      no      209
27127  27128   29       services    single  secondary      no       40

      housing loan    contact  day month  duration  campaign  pdays  previous  \
0         yes   no   cellular    3   apr       939         1     -1         0
1          no   no   cellular   18   feb       172        10     -1         0
2          no   no   cellular   13   apr       567         1    595         2
3          no   no   cellular   25   jan       423         1     -1         0
4          no   no   cellular   30   apr       502         1      9         2
5         yes   no    unknown    2   jun       707        14     -1         0
6         yes   no   cellular    6   sep       908         1    185         9
7         yes   no   cellular   18   may       442         1    266         8
8         yes   no   cellular    7   may       895         2    295         2
9          no   no  telephone   10   aug       235         1    102         2
10         no   no   cellular   12   aug       582         1     -1         0
11        yes   no    unknown   30   may      1097        15     -1         0
12         no  yes    unknown   31   aug        34         1     -1         0
13        yes   no   cellular    5   mar       112         2    106         1
14        yes   no    unknown    4   jun       984         2     -1         0
15         no   no   cellular   27   apr       388         3     -1         0
16         no   no   cellular   14   aug       185         1     -1         0
17         no   no   cellular   15   jul       268         5    181         2
18        yes   no    unknown   13   may       916         2     -1         0
19        yes   no   cellular   22   jul       120         1     -1         0
20        yes  yes   cellular    5   may       145         1     -1         0
21         no   no   cellular   11   sep        96         2     -1         0
22        yes   no   cellular   17   jul       795         1     -1         0
23        yes   no  telephone    6   feb       112         2     -1         0
24        yes   no    unknown    6   jun       354         2     -1         0
25        yes   no   cellular   11   may       798         2     -1         0
26         no   no   cellular   11   aug       155         2     -1         0
27         no   no   cellular    2   feb       297         1     -1         0
28        yes   no   cellular   22   jul       261         1     -1         0
29        yes   no   cellular    8   apr        95         1     -1         0
...       ...  ...        ...  ...   ...       ...       ...    ...       ...
27098      no  yes  telephone   19   nov       278         7     -1         0
27099     yes   no    unknown   29   may       106         4     -1         0
27100      no   no   cellular    8   aug        71         2     -1         0
27101     yes   no    unknown    2   jun       171         1     -1         0
27102     yes   no    unknown   12   may      1875         4     -1         0
27103      no   no   cellular   17   apr       351         1     -1         0
27104      no   no  telephone   29   jul       175         2     -1         0
27105      no   no   cellular   27   oct       418         2     -1         0
27106      no  yes    unknown   17   jun       717         1     -1         0
27107     yes  yes   cellular   15   jul       323         3     -1         0
27108     yes   no   cellular   18   jul       968         1     -1         0
27109     yes   no    unknown   14   may       293         3     -1         0
27110     yes  yes   cellular   18   jul       252         6     -1         0
27111     yes   no    unknown   13   may       342         3     -1         0
27112     yes   no  telephone   24   jul        32         1     -1         0
27113     yes  yes    unknown   29   may       553         1     -1         0
27114     yes   no    unknown   26   may       402         2     -1         0
27115      no   no   cellular   11   aug       370         1     91         7
27116     yes   no   cellular   11   may        82         2     -1         0
27117      no   no   cellular   26   aug       191         2     -1         0
27118      no   no   cellular    5   feb        85         2      8         2
27119     yes   no   cellular    2   feb        45         1     -1         0
27120      no   no   cellular   12   may       801         1     86         2
27121     yes   no   cellular   25   may       143         1     -1         0
27122     yes   no   cellular   21   jul       118         3     -1         0
27123     yes   no   cellular    2   feb       279         2    269         2
27124     yes   no    unknown   15   may       362         3     -1         0
27125     yes   no    unknown    8   may       405         1     -1         0
27126      no   no   cellular   12   aug        76         4     -1         0
27127     yes   no   cellular   18   may       105         1    355         2

      poutcome  y
0      unknown  1
1      unknown  1
2      failure  1
3      unknown  1
4      success  1
5      unknown  1
6      success  1
7      failure  1
8      failure  1
9      failure  1
10     unknown  1
11     unknown  1
12     unknown  1
13     failure  1
14     unknown  1
15     unknown  1
16     unknown  1
17     failure  1
18     unknown  1
19     unknown  0
20     unknown  0
21     unknown  0
22     unknown  1
23     unknown  0
24     unknown  0
25     unknown  0
26     unknown  0
27     unknown  0
28     unknown  0
29     unknown  0
...        ... ..
27098  unknown  0
27099  unknown  0
27100  unknown  0
27101  unknown  0
27102  unknown  0
27103  unknown  0
27104  unknown  0
27105  unknown  1
27106  unknown  0
27107  unknown  0
27108  unknown  1
27109  unknown  0
27110  unknown  0
27111  unknown  0
27112  unknown  0
27113  unknown  0
27114  unknown  0
27115  success  1
27116  unknown  0
27117  unknown  0
27118    other  0
27119  unknown  0
27120  failure  0
27121  unknown  0
27122  unknown  0
27123    other  0
27124  unknown  0
27125  unknown  0
27126  unknown  0
27127  failure  0

[27128 rows x 18 columns]

In [ ]:
names = ["job","marial", "education","default" , "balance",  "housing",]



評価用データと同じ形にする。

In [18]:

# One hot encoding column# One h 
names = ["job", "marital", "education", "default", "housing", "loan", "contact", "month", "poutcome"]

# One hot encorde the training
df = pd.read_csv("train.csv")
x_df = df.iloc[:, :-1]
y_df = df.iloc[:, -1]

onehot_df = pd.get_dummies(x_df, columns=names, drop_first=True)
onehot_df = pd.concat([onehot_df, y_df], axis=1)

onehot_df.to_csv("onehot_train.csv")

# One hot encorde the test
df = pd.read_csv("test.csv")

onehot_df = pd.get_dummies(df, columns=names, drop_first=True)

onehot_df.to_csv("onehot_test.csv")

In [32]:
df = pd.read_csv("onehot_train.csv")
x_array = np.array(df.iloc[:, :-1])
y_array = np.array(df.iloc[:, -1])

x_train, x_val, y_train, y_val = train_test_split(x_array, y_array, test_size=0.2)

model = GradientBoostingClassifier()
model.fit(x_train, y_train)

def auc_score(x, y, m):
    return roc_auc_score(y, m.predict_proba(x)[:, 1])
    
print("train score:", auc_score(x_train, y_train, model))
print("test score:", auc_score(x_val, y_val, model))

train score: 0.9323218141507964
test score: 0.9212354919841231

In [33]:
df = pd.read_csv("onehot_test.csv")
x = np.array(df)
df = pd.read_csv("onehot_test.csv")
x = np.array(df)

pred = model.predict_proba(x)
pred_df = pd.DataFrame({"pred": pred[:, 1]})
pred_df.index += 1
pred_df.to_csv("submit.csv", header=False)
pred = model.predict_proba(x)
pred_df = pd.DataFrame({"pred": pred[:, 1]})
pred_df.index += 1
pred_df.to_csv("submit.csv", header=False)